kind: Service
apiVersion: v1
metadata:
  name: jaeger-tracing-agent
  namespace: default 
  labels:
    app.kubernetes.io/component: agent
    app.kubernetes.io/instance: jaeger-tracing
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/version: 1.28.0
    helm.sh/chart: jaeger-0.51.5
spec:
  ports:
    - name: jaeger-compact
      protocol: UDP
      port: 6831
      targetPort: jaeger-compact
  selector:
    app.kubernetes.io/component: agent
    app.kubernetes.io/instance: jaeger-tracing
    app.kubernetes.io/name: jaeger
  type: LoadBalancer
 